name: Check CSV order

on:

  push:
    branches:
      - ci-check-csv-ordering

  pull_request:


jobs:
  check-order:
    runs-on: [ubuntu-latest]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sorted version
        run: cat fate-product-list.csv | sort > fate-product-list-sorted.csv

      - name: Compare sorted and actual list
        run: diff fate-product-list.csv fate-product-list-sorted.csv