name: Check CSV order

on:

  push:
    branches:
      - ci-check-csv-ordering

  pull_request:


jobs:
  check-order:
    runs-on: [ubuntu-latest]

    steps:

      - name: Checkout
        uses: actions/checkout@v4
