name: Check CSV order

on:

  pull_request:


jobs:
  check-order:
    runs-on: [ubuntu-latest]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate header-free version
        run: tail -n +2 fate-product-list.csv > headerless.csv

      - name: Generate sorted version
        run: cat headerless.csv | LC_ALL=en_US.UTF-8 sort | head -c -1 > sorted.csv

      - name: Compare sorted and actual list
        run: diff --color=always -u headerless.csv sorted.csv