name: Check CSV order

on:

  push:
    branches:
      - ci-check-csv-ordering

  pull_request:


jobs:
  check-order:
    runs-on: [ubuntu-latest]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate header-free version
        run: tail -n +2 fate-product-list.csv > headerless.csv

      - name: Generate sorted version
        run: cat headerless.csv | LC_ALL=C sort > sorted.csv

      - name: Compare sorted and actual list
        run: diff --color -u headerless.csv sorted.csv