name: PR Merge Test

on:
  pull_request:
    types:
      - closed
    branches:
      - 'test-pr-merged-workflow'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_OBJ: ${{ toJson(github) }}
    steps:
      - run: |
          echo The PR was merged
          echo GITHUB_REF ${GITHUB_REF}
          echo GITHUB_SHA ${GITHUB_SHA}
          echo ${GITHUB_OBJ} | jq .
