name: PR Merge Test

on:
  pull_request:
    types:
      - closed
    branches:
      - 'test-pr-merged-workflow'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
          git show ${{ toJson(github.event.pull_request.base.sha) }}
          git show ${{ toJson(github.event.pull_request.head.sha) }}
          if git diff --name-only ${{ toJson(github.event.pull_request.base.sha) }} ${{ toJson(github.event.pull_request.head.sha) }} | grep fate-product-list.csv > /dev/null
          then
            if npm version -m "Version updated to %s because product list changed."
            then
              echo "Version updated to "  $( jq .version package.json ) "."
              git describe
            else
              echo "Couldn't update version for some reason."
            fi
          else
            echo "No changes to product list."
          fi
            
